micronaut:
  application:
    name: examples
  server:
    port: 8080
    cors:
      enabled: true
  #tag::oauth2[]
  security:
    oauth2:
      clients:
        cognito: # <1>
          client-secret: '${OAUTH_CLIENT_SECRET}' # <2>
          client-id: '${OAUTH_CLIENT_ID}' # <3>
          openid:
            issuer: 'https://cognito-idp.${COGNITO_REGION}.amazonaws.com/${COGNITO_POOL_ID}/' # <4>
    token:
      jwt:
        cookie:
          enabled: true # <5>
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
    endpoints:
      logout:
        enabled: true # <6>
        get-allowed: true # <7>
#end::oauth2[]
